VS filter: testpath:TestAssembly:Examen2/Feature:Examen/Scenario:Order+an+array+of+employees
Discovering target: Default
Discovering tests from assembly: C:\Users\Raim\Documents\Visual Studio 2015\Projects\Examen2\Examen2\bin\Debug\Examen2.dll
Appdomain Disposed
Test Suite Dump
#0: Examen2/Default - 
#1: Default - 
#2: Examen2 - 
#3: Examen - 
#5: Order an array of employees - TestAssembly:Examen2/Feature:Examen/Scenario:Order+an+array+of+employees
End: Test Suite Dump
Thread#0:Scheduler: get next test for thread
Thread#:Scheduler: testitem #5 from normal test queue 
Thread#0:Scheduler: considering testitem #5 for thread
Thread#0:Scheduler: using testitem #5 for thread
Thread#0:Scheduler: Test #5 is scheduled for thread
Thread#0:Scheduler: with testItemExecutionIndex 0
Thread #0: creating new test thread executor for Examen2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (target: Default)
Loading SpecRun type 'TechTalk.SpecRun.Framework.TestAssemblyExecutor' from: C:\Users\Raim\AppData\Local\Temp\VisualStudioTestExplorerExtensions\SpecRun.Runner.1.5.2\tools\TechTalk.SpecRun.Framework.Executor.dll
Thread#0: Test #5/0 is started on thread #0
Thread#0:B:Given I have the following employees
Thread#0:B:  --- table step argument ---
Thread#0:B:  | Code | Name |
Thread#0:B:  | 1    | C    |
Thread#0:B:  | 2    | A    |
Thread#0:B:  | 3    | B    |
Thread#0:T:done: ExamenSteps.GivenIHaveTheFollowingEmployees(<table>) (0.1s)
Thread#0:B:When we QUICKSORT by name
Thread#0:T:error: Index was outside the bounds of the array.
Thread#0:B:Then the list should be like this
Thread#0:B:  --- table step argument ---
Thread#0:B:  | Code | Name |
Thread#0:B:  | 2    | A    |
Thread#0:B:  | 3    | B    |
Thread#0:B:  | 1    | C    |
Thread#0:T:skipped because of previous errors
Thread#0:Scheduler: reschedule tests for testitem #0
Thread#0:Scheduler: get next test for thread
Thread#:Scheduler: dequeuing a rescheduled testitem: #5
Thread#0:Scheduler: considering testitem #5 for thread
Thread#0:Scheduler: using testitem #5 for thread
Thread#0:Scheduler: Test #5 is scheduled for thread
Thread#0:Scheduler: with testItemExecutionIndex 0
Thread#0: Test #5/0 is finished on thread #0 as Failed within 1.2098269 seconds
Thread#0: Test #5/1 is started on thread #0
Thread#0:B:Given I have the following employees
Thread#0:B:  --- table step argument ---
Thread#0:B:  | Code | Name |
Thread#0:B:  | 1    | C    |
Thread#0:B:  | 2    | A    |
Thread#0:B:  | 3    | B    |
Thread#0:T:done: ExamenSteps.GivenIHaveTheFollowingEmployees(<table>) (0.0s)
Thread#0:B:When we QUICKSORT by name
Thread#0:T:error: Index was outside the bounds of the array.
Thread#0:B:Then the list should be like this
Thread#0:B:  --- table step argument ---
Thread#0:B:  | Code | Name |
Thread#0:B:  | 2    | A    |
Thread#0:B:  | 3    | B    |
Thread#0:B:  | 1    | C    |
Thread#0:T:skipped because of previous errors
Thread#0:Scheduler: get next test for thread
Thread#:Scheduler: dequeuing a rescheduled testitem: #5
Thread#0:Scheduler: considering testitem #5 for thread
Thread#0:Scheduler: using testitem #5 for thread
Thread#0:Scheduler: Test #5 is scheduled for thread
Thread#0:Scheduler: with testItemExecutionIndex 0
Thread#0: Test #5/1 is finished on thread #0 as Failed within 0.0100088 seconds
Thread#0: Test #5/2 is started on thread #0
Thread#0:B:Given I have the following employees
Thread#0:B:  --- table step argument ---
Thread#0:B:  | Code | Name |
Thread#0:B:  | 1    | C    |
Thread#0:B:  | 2    | A    |
Thread#0:B:  | 3    | B    |
Thread#0:T:done: ExamenSteps.GivenIHaveTheFollowingEmployees(<table>) (0.0s)
Thread#0:B:When we QUICKSORT by name
Thread#0:T:error: Index was outside the bounds of the array.
Thread#0:B:Then the list should be like this
Thread#0:B:  --- table step argument ---
Thread#0:B:  | Code | Name |
Thread#0:B:  | 2    | A    |
Thread#0:B:  | 3    | B    |
Thread#0:B:  | 1    | C    |
Thread#0:T:skipped because of previous errors
Thread#0:Scheduler: get next test for thread
Thread#:Scheduler: at the end of normal test queue
Thread#0:Scheduler: enumerator for thread is at end
Thread#0:Scheduler: No more tests for thread 
Thread#0: Test #5/2 is finished on thread #0 as Failed within 0.010007 seconds
Appdomain Disposed
Thread#-1:Scheduler: get next test for thread
Thread#:Scheduler: at the end of normal test queue
Thread#-1:Scheduler: enumerator for thread is at end
Total: 1 (test executions: 3)
Succeeded: 0
Ignored: 0
Pending: 0
Skipped: 0
Failed: 1
